[package]
name = "ss_server"
version = "0.1.0"
authors = ["ZiJiaW"]
edition = "2018"

[dependencies]
ss_local = {path = "../ss_local"}
tokio = { version = "0.2.10", features = ["full"] }
futures = "0.3"