[package]
name = "ss_server"
version = "0.1.0"
authors = ["ZiJiaW <964513305@qq.com>"]
edition = "2018"

[dependencies]
ss_local = {path = "../ss_local"}
tokio = "0.1"
futures = "0.1"
trust-dns-resolver = "^0.9"
trust-dns = "^0.14"