[package]
name = "ss_gui"
version = "0.1.0"
authors = ["ZiJiaW <964513305@qq.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"
futures = "0.1"
bytes = "0.4"
trust-dns-resolver = "^0.9"
trust-dns = "^0.14"